// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/persistence/schema/types/base/v1beta1/fact.proto

package base

import (
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/regen-network/cosmos-proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//  option (cosmos_proto.implements_interface) = "Fact";
	HashID     *types.Any `protobuf:"bytes,1,opt,name=hashID,proto3" json:"hashID,omitempty"`
	TypeID     *types.Any `protobuf:"bytes,2,opt,name=typeID,proto3" json:"typeID,omitempty"`
	Signatures *types.Any `protobuf:"bytes,3,opt,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persistence_schema_types_base_v1beta1_fact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persistence_schema_types_base_v1beta1_fact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescGZIP(), []int{0}
}

//func (x *Fact) GetHashID() *anypb.Any {
//	if x != nil {
//		return x.HashID
//	}
//	return nil
//}
//
//func (x *Fact) GetTypeID() *anypb.Any {
//	if x != nil {
//		return x.TypeID
//	}
//	return nil
//}
//
//func (x *Fact) GetSignatures() *anypb.Any {
//	if x != nil {
//		return x.Signatures
//	}
//	return nil
//}

var File_proto_persistence_schema_types_base_v1beta1_fact_proto protoreflect.FileDescriptor

var file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x66, 0x61,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a,
	0x2b, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x74,
	0x12, 0x34, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x42, 0x06, 0xca, 0xb4, 0x2d, 0x02, 0x49, 0x44, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x68, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x42, 0x06, 0xca, 0xb4,
	0x2d, 0x02, 0x49, 0x44, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12, 0x43, 0x0a, 0x0a,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x42, 0x0d, 0xca, 0xb4, 0x2d, 0x09, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescOnce sync.Once
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescData = file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDesc
)

func file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescGZIP() []byte {
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescOnce.Do(func() {
		file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescData)
	})
	return file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDescData
}

var file_proto_persistence_schema_types_base_v1beta1_fact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_persistence_schema_types_base_v1beta1_fact_proto_goTypes = []interface{}{
	(*Fact)(nil),      // 0: persistence.schema.types.base.v1beta1.fact
	(*types.Any)(nil), // 1: google.protobuf.Any
}
var file_proto_persistence_schema_types_base_v1beta1_fact_proto_depIdxs = []int32{
	1, // 0: persistence.schema.types.base.v1beta1.fact.hashID:type_name -> google.protobuf.Any
	1, // 1: persistence.schema.types.base.v1beta1.fact.typeID:type_name -> google.protobuf.Any
	1, // 2: persistence.schema.types.base.v1beta1.fact.signatures:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_persistence_schema_types_base_v1beta1_fact_proto_init() }
func file_proto_persistence_schema_types_base_v1beta1_fact_proto_init() {
	if File_proto_persistence_schema_types_base_v1beta1_fact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_persistence_schema_types_base_v1beta1_fact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_persistence_schema_types_base_v1beta1_fact_proto_goTypes,
		DependencyIndexes: file_proto_persistence_schema_types_base_v1beta1_fact_proto_depIdxs,
		MessageInfos:      file_proto_persistence_schema_types_base_v1beta1_fact_proto_msgTypes,
	}.Build()
	File_proto_persistence_schema_types_base_v1beta1_fact_proto = out.File
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_rawDesc = nil
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_goTypes = nil
	file_proto_persistence_schema_types_base_v1beta1_fact_proto_depIdxs = nil
}
