// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/persistence/assets/orders/transactions/define/v1beta1/tx.proto

package define

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation Error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type message struct {
	From                    github_com_cosmos_cosmos_sdk_types.AccAddress                        `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"from" valid:"required~required field from missing"`
	FromID                  github_com_persistenceOne_persistenceSDK_schema_types.ID             `protobuf:"bytes,2,opt,name=from_iD,json=fromID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"fromID" valid:"required~required field fromID missing"`
	ImmutableMetaProperties github_com_persistenceOne_persistenceSDK_schema_types.MetaProperties `protobuf:"bytes,3,opt,name=immutableMetaProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.MetaProperties" json:"immutableMetaProperties" valid:"required~required field immutableMetaProperties missing"`
	ImmutableProperties     github_com_persistenceOne_persistenceSDK_schema_types.Properties     `protobuf:"bytes,4,opt,name=immutableProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"immutableProperties" valid:"required~required field immutableProperties missing"`
	MutableMetaProperties   github_com_persistenceOne_persistenceSDK_schema_types.MetaProperties `protobuf:"bytes,5,opt,name=mutableMetaProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.MetaProperties" json:"mutableMetaProperties" valid:"required~required field mutableMetaProperties missing"`
	MutableProperties       github_com_persistenceOne_persistenceSDK_schema_types.Properties     `protobuf:"bytes,6,opt,name=mutableProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"mutableProperties" valid:"required~required field mutableProperties missing"`
}

func (m message) Reset()         { m = message{} }
func (m message) String() string { return proto.CompactTextString(&m) }
func (message) ProtoMessage()    {}
func (*message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fdf732d1732605e, []int{0}
}
func (m *message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *message) XXX_Size() int {
	return m.Size()
}
func (m *message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*message)(nil), "persistence.assets.orders.transactions.define.v1beta1.message")
}

func init() {
	proto.RegisterFile("proto/persistence/assets/orders/transactions/define/v1beta1/tx.proto", fileDescriptor_1fdf732d1732605e)
}

var fileDescriptor_1fdf732d1732605e = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x13, 0xdd, 0xed, 0xea, 0xdc, 0x8c, 0x88, 0xc5, 0x43, 0x22, 0x1e, 0x44, 0x90, 0x9d,
	0x61, 0x91, 0xbd, 0x08, 0x82, 0x2d, 0x29, 0x58, 0x54, 0x94, 0x7a, 0xf3, 0x60, 0x99, 0x24, 0xaf,
	0xe9, 0x60, 0x27, 0x13, 0xe6, 0xbd, 0x16, 0xeb, 0xd1, 0x83, 0x78, 0xf4, 0x23, 0xf4, 0xa3, 0x78,
	0xec, 0xb1, 0x47, 0xf1, 0x50, 0xa4, 0xbd, 0xf8, 0x31, 0xa4, 0x49, 0xa8, 0x91, 0xc6, 0x83, 0xe2,
	0x9e, 0x26, 0x61, 0xf8, 0xff, 0x7e, 0xff, 0x37, 0xf0, 0x58, 0x98, 0x5b, 0x43, 0x46, 0xe4, 0x60,
	0x51, 0x21, 0x41, 0x16, 0x83, 0x90, 0x88, 0x40, 0x28, 0x8c, 0x4d, 0xc0, 0xa2, 0x20, 0x2b, 0x33,
	0x94, 0x31, 0x29, 0x93, 0xa1, 0x48, 0x60, 0xa4, 0x32, 0x10, 0xb3, 0xb3, 0x08, 0x48, 0x9e, 0x09,
	0x7a, 0xc7, 0x8b, 0xb8, 0x77, 0x5e, 0xcb, 0xf3, 0x32, 0xcf, 0xcb, 0x3c, 0xaf, 0xe7, 0x79, 0x99,
	0xe7, 0x55, 0xfe, 0xd6, 0x5d, 0x1a, 0x2b, 0x9b, 0x0c, 0x73, 0x69, 0x69, 0x2e, 0xca, 0x22, 0xa9,
	0x49, 0xcd, 0xaf, 0xaf, 0x12, 0x7f, 0xe7, 0xcb, 0x31, 0x3b, 0xd1, 0x80, 0x28, 0x53, 0xf0, 0xfa,
	0xec, 0x68, 0x64, 0x8d, 0x6e, 0xbb, 0xb7, 0xdd, 0x7b, 0x57, 0xbb, 0xe7, 0xcb, 0x75, 0xe0, 0x7c,
	0x5b, 0x07, 0xa7, 0xa9, 0xa2, 0xf1, 0x34, 0xe2, 0xb1, 0xd1, 0x22, 0x36, 0xa8, 0x0d, 0x56, 0xc7,
	0x29, 0x26, 0x6f, 0x05, 0xcd, 0x73, 0x40, 0xde, 0x89, 0xe3, 0x4e, 0x92, 0x58, 0x40, 0x1c, 0x14,
	0x08, 0xef, 0x0d, 0x3b, 0xd9, 0x9d, 0x43, 0x15, 0xb6, 0x2f, 0x15, 0xb4, 0x5e, 0x45, 0x7b, 0x54,
	0xa3, 0xd5, 0x26, 0x7b, 0x91, 0x41, 0xfd, 0xf7, 0x55, 0xf8, 0x54, 0x60, 0x3c, 0x06, 0x2d, 0x05,
	0x01, 0xd2, 0xb0, 0xb4, 0xf4, 0xc3, 0x41, 0x6b, 0x47, 0xed, 0x87, 0xde, 0x47, 0x97, 0xdd, 0x54,
	0x5a, 0x4f, 0x49, 0x46, 0x13, 0x78, 0x0e, 0x24, 0x5f, 0x5a, 0x93, 0x83, 0x25, 0x05, 0xd8, 0xbe,
	0x5c, 0x08, 0x9f, 0x55, 0xc2, 0xf0, 0xaf, 0x85, 0x85, 0xeb, 0x77, 0xe6, 0xe0, 0x4f, 0x32, 0xef,
	0x3d, 0xbb, 0xbe, 0xbf, 0xaa, 0x75, 0x38, 0x2a, 0x3a, 0x3c, 0xa9, 0x3a, 0x3c, 0xfe, 0xb7, 0x0e,
	0x35, 0x7f, 0x93, 0xc4, 0xfb, 0xe0, 0xb2, 0x1b, 0xcd, 0x4f, 0x70, 0x7c, 0x01, 0x4f, 0xd0, 0xac,
	0xf2, 0x66, 0xec, 0xda, 0xe1, 0xf8, 0xad, 0xff, 0x3c, 0xfe, 0xa1, 0xe2, 0xe1, 0x95, 0x4f, 0x8b,
	0xc0, 0xf9, 0xb1, 0x08, 0x9c, 0x6e, 0x6f, 0xb9, 0xf1, 0xdd, 0xd5, 0xc6, 0x77, 0xbf, 0x6f, 0x7c,
	0xf7, 0xf3, 0xd6, 0x77, 0x56, 0x5b, 0xdf, 0xf9, 0xba, 0xf5, 0x9d, 0xd7, 0xf7, 0xb5, 0x49, 0xa6,
	0x13, 0xd8, 0x2f, 0x9c, 0xca, 0x08, 0x6c, 0x26, 0x27, 0x4d, 0x9b, 0x17, 0xb5, 0x8a, 0x85, 0x78,
	0xf0, 0x33, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x34, 0x4b, 0x3f, 0xb7, 0x03, 0x00, 0x00,
}

func (m *message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MutableProperties.Size() > 0 {
		i -= m.MutableProperties.Size()
		if _, err := m.MutableProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(m.MutableProperties.Size()))
		i--
		dAtA[i] = 0x32
	}
	if m.MutableMetaProperties.Size() > 0 {
		i -= m.MutableMetaProperties.Size()
		if _, err := m.MutableMetaProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(m.MutableMetaProperties.Size()))
		i--
		dAtA[i] = 0x2a
	}
	if m.ImmutableProperties.Size() > 0 {
		i -= m.ImmutableProperties.Size()
		if _, err := m.ImmutableProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(m.ImmutableProperties.Size()))
		i--
		dAtA[i] = 0x22
	}
	if m.ImmutableMetaProperties.Size() > 0 {
		i -= m.ImmutableMetaProperties.Size()
		if _, err := m.ImmutableMetaProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(m.ImmutableMetaProperties.Size()))
		i--
		dAtA[i] = 0x1a
	}
	if m.FromID.Size() > 0 {
		i -= m.FromID.Size()
		if _, err := m.FromID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(m.FromID.Size()))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.FromID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ImmutableMetaProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ImmutableProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MutableMetaProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MutableProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = github_com_cosmos_cosmos_sdk_types.AccAddress(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImmutableMetaProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ImmutableMetaProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImmutableProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ImmutableProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableMetaProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableMetaProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
