// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/persistence/assets/orders/transactions/immediate/v1beta1/tx.proto

package immediate

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type message struct {
	From                    github_com_cosmos_cosmos_sdk_types.AccAddress                        `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"from" valid:"required~required field from missing"`
	FromID                  github_com_persistenceOne_persistenceSDK_schema_types.ID             `protobuf:"bytes,2,opt,name=fromID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"fromID" valid:"required~required field fromID missing"`
	ClassificationID        github_com_persistenceOne_persistenceSDK_schema_types.ID             `protobuf:"bytes,3,opt,name=classificationID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"classificationID" valid:"required~required field classificationID missing"`
	MakerOwnableID          github_com_persistenceOne_persistenceSDK_schema_types.ID             `protobuf:"bytes,4,opt,name=makerOwnableID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"makerOwnableID" valid:"required~required field makerOwnableID missing"`
	TakerOwnableID          github_com_persistenceOne_persistenceSDK_schema_types.ID             `protobuf:"bytes,5,opt,name=takerOwnableID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"takerOwnableID" valid:"required~required field takerOwnableID missing"`
	ExpiresIn               github_com_persistenceOne_persistenceSDK_schema_types.Height         `protobuf:"bytes,6,opt,name=expiresIn,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Height" json:"expiresIn" valid:"required~required field expiresIn missing"`
	MakerOwnableSplit       github_com_cosmos_cosmos_sdk_types.Dec                               `protobuf:"bytes,7,opt,name=makerOwnableSplit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"makerOwnableSplit" valid:"required~required field makerOwnableSplit missing"`
	TakerOwnableSplit       github_com_cosmos_cosmos_sdk_types.Dec                               `protobuf:"bytes,8,opt,name=takerOwnableSplit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"takerOwnableSplit" valid:"required~required field takerOwnableSplit missing"`
	ImmutableMetaProperties github_com_persistenceOne_persistenceSDK_schema_types.MetaProperties `protobuf:"bytes,9,opt,name=immutableMetaProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.MetaProperties" json:"immutableMetaProperties" valid:"required~required field immutableMetaProperties missing"`
	ImmutableProperties     github_com_persistenceOne_persistenceSDK_schema_types.Properties     `protobuf:"bytes,10,opt,name=immutableProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"immutableProperties" valid:"required~required field immutableProperties missing"`
	MutableMetaProperties   github_com_persistenceOne_persistenceSDK_schema_types.MetaProperties `protobuf:"bytes,11,opt,name=mutableMetaProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.MetaProperties" json:"mutableMetaProperties" valid:"required~required field mutableMetaProperties missing"`
	MutableProperties       github_com_persistenceOne_persistenceSDK_schema_types.Properties     `protobuf:"bytes,12,opt,name=mutableProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"mutableProperties" valid:"required~required field mutableProperties missing"`
}

func (m message) Reset()         { m = message{} }
func (m message) String() string { return proto.CompactTextString(m) }
func (message) ProtoMessage()    {}
func (*message) Descriptor() ([]byte, []int) {
	return fileDescriptor_94b91c4bf6fd560f, []int{0}
}
func (m *message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *message) XXX_Size() int {
	return m.Size()
}
func (m *message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*message)(nil), "persistence.assets.orders.transactions.immediate.v1beta1.message")
}

func init() {
	proto.RegisterFile("proto/persistence/assets/orders/transactions/immediate/v1beta1/tx.proto", fileDescriptor_94b91c4bf6fd560f)
}

var fileDescriptor_94b91c4bf6fd560f = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0xd4, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc0, 0xf1, 0x5d, 0xad, 0x6d, 0x33, 0x8a, 0xd8, 0x11, 0x71, 0xf1, 0xb0, 0x11, 0x0f, 0xc5,
	0x4b, 0x77, 0x28, 0x22, 0x14, 0xf1, 0xd0, 0x96, 0x05, 0xb3, 0xa8, 0x54, 0xd2, 0x8b, 0x88, 0x20,
	0x93, 0xdd, 0xd7, 0x64, 0xe8, 0xce, 0xce, 0x32, 0xef, 0xa5, 0xb6, 0x1e, 0x3d, 0x88, 0x47, 0xff,
	0x00, 0x0f, 0xfd, 0x73, 0x7a, 0xec, 0x51, 0x3c, 0x14, 0x49, 0x2e, 0xfe, 0x19, 0x92, 0xcd, 0x92,
	0x6e, 0xdc, 0x14, 0x24, 0xc4, 0xd3, 0xe6, 0x07, 0x7c, 0xbe, 0xef, 0x0d, 0xcb, 0xb0, 0x17, 0xb9,
	0x35, 0x64, 0x44, 0x0e, 0x16, 0x15, 0x12, 0x64, 0x31, 0x08, 0x89, 0x08, 0x84, 0xc2, 0xd8, 0x04,
	0x2c, 0x0a, 0xb2, 0x32, 0x43, 0x19, 0x93, 0x32, 0x19, 0x0a, 0xa5, 0x35, 0x24, 0x4a, 0x12, 0x88,
	0xa3, 0xcd, 0x0e, 0x90, 0xdc, 0x14, 0x74, 0x1c, 0x14, 0x02, 0xdf, 0xaa, 0x10, 0xc1, 0x98, 0x08,
	0xc6, 0x44, 0x50, 0x25, 0x82, 0x09, 0x11, 0x94, 0xc4, 0x83, 0x75, 0xea, 0x29, 0x9b, 0x7c, 0xc8,
	0xa5, 0xa5, 0x13, 0x31, 0x1e, 0xa7, 0x6b, 0xba, 0xe6, 0xf2, 0xd3, 0xb8, 0xf0, 0xe8, 0x3b, 0x63,
	0x2b, 0x1a, 0x10, 0x65, 0x17, 0x78, 0xc4, 0x96, 0x0e, 0xac, 0xd1, 0x9e, 0xfb, 0xd0, 0x7d, 0xdc,
	0xd8, 0x7d, 0x7a, 0x76, 0xd1, 0x74, 0x7e, 0x5e, 0x34, 0x37, 0xba, 0x8a, 0x7a, 0xfd, 0x4e, 0x10,
	0x1b, 0x2d, 0x62, 0x83, 0xda, 0x60, 0xf9, 0xd8, 0xc0, 0xe4, 0x50, 0xd0, 0x49, 0x0e, 0x18, 0xec,
	0xc4, 0xf1, 0x4e, 0x92, 0x58, 0x40, 0x6c, 0x17, 0x04, 0x7f, 0xcb, 0x96, 0x47, 0xcf, 0x28, 0xf4,
	0xae, 0x15, 0xd8, 0x76, 0x89, 0x6d, 0x55, 0xb0, 0xca, 0x6e, 0x7b, 0x19, 0x54, 0xbf, 0xee, 0x87,
	0x2f, 0x05, 0xc6, 0x3d, 0xd0, 0xb2, 0xf4, 0xa3, 0xb0, 0x5d, 0x7a, 0x3c, 0x65, 0x77, 0xe2, 0x54,
	0x22, 0xaa, 0x03, 0x15, 0xcb, 0xd1, 0xf6, 0x51, 0xe8, 0x5d, 0x5f, 0x50, 0xa3, 0x26, 0xf3, 0x1e,
	0xbb, 0xad, 0xe5, 0x21, 0xd8, 0xbd, 0x8f, 0x99, 0xec, 0xa4, 0x10, 0x85, 0xde, 0xd2, 0x82, 0x5a,
	0x7f, 0xb9, 0xa3, 0x12, 0x4d, 0x97, 0x6e, 0x2c, 0xaa, 0x34, 0xed, 0xf2, 0x0e, 0x6b, 0xc0, 0x71,
	0xae, 0x2c, 0x60, 0x94, 0x79, 0xcb, 0x45, 0x24, 0x2c, 0x23, 0xcf, 0xe7, 0x8b, 0xb4, 0x40, 0x75,
	0x7b, 0xd4, 0xbe, 0x64, 0xf9, 0x7b, 0xb6, 0x56, 0xdd, 0x6f, 0x3f, 0x4f, 0x15, 0x79, 0x2b, 0x45,
	0x2b, 0x28, 0x5b, 0xeb, 0xff, 0xf0, 0x5e, 0x85, 0x10, 0xb7, 0xeb, 0xd0, 0x48, 0xa7, 0x9a, 0xbe,
	0x3a, 0x9f, 0x5e, 0x83, 0xf8, 0x17, 0x97, 0xdd, 0x57, 0x5a, 0xf7, 0x69, 0xf4, 0xd3, 0x6b, 0x20,
	0xf9, 0xc6, 0x9a, 0x1c, 0x2c, 0x29, 0x40, 0xaf, 0x51, 0x44, 0x5e, 0x95, 0x91, 0x70, 0xbe, 0xe3,
	0x9a, 0x36, 0xdb, 0x57, 0xc5, 0xf8, 0x27, 0x76, 0x77, 0xf2, 0x57, 0x65, 0x06, 0x56, 0xcc, 0xd0,
	0x2a, 0x67, 0xd8, 0x9e, 0x6f, 0x86, 0x4a, 0x7f, 0x56, 0x84, 0x7f, 0x76, 0xd9, 0xbd, 0xd9, 0x47,
	0x70, 0xf3, 0x3f, 0x1c, 0xc1, 0xec, 0x14, 0x3f, 0x62, 0x6b, 0xf5, 0xf5, 0x6f, 0x2d, 0x78, 0xfd,
	0x7a, 0xe2, 0xd9, 0xea, 0xd7, 0xd3, 0xa6, 0xf3, 0xfb, 0xb4, 0xe9, 0xec, 0xb6, 0xce, 0x06, 0xbe,
	0x7b, 0x3e, 0xf0, 0xdd, 0x5f, 0x03, 0xdf, 0xfd, 0x36, 0xf4, 0x9d, 0xf3, 0xa1, 0xef, 0xfc, 0x18,
	0xfa, 0xce, 0xbb, 0x40, 0x9b, 0xa4, 0x9f, 0xc2, 0xe4, 0x4a, 0x57, 0x19, 0x81, 0xcd, 0x64, 0x7a,
	0xc5, 0xdd, 0xde, 0x59, 0x2e, 0xee, 0xdb, 0x27, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x24,
	0x46, 0xb5, 0x1c, 0x06, 0x00, 0x00,
}

func (m *message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MutableProperties.Size() > 0 {
		i -= m.MutableProperties.Size()
		if _, err := m.MutableProperties.MarshalTo(dAtA[i:]); err!= nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.MutableProperties.Size()))
		i--
		dAtA[i] = 0x62
	}
	if m.MutableMetaProperties.Size() > 0 {
		i -= m.MutableMetaProperties.Size()
		if _, err := m.MutableMetaProperties.MarshalTo(dAtA[i:]); err!= nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.MutableMetaProperties.Size()))
		i--
		dAtA[i] = 0x5a
	}
	if m.ImmutableProperties.Size() > 0 {
		i -= m.ImmutableProperties.Size()
		if _, err := m.ImmutableProperties.MarshalTo(dAtA[i:]); err!= nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ImmutableProperties.Size()))
		i--
		dAtA[i] = 0x52
	}
	if m.ImmutableMetaProperties.Size() > 0 {
		i -= m.ImmutableMetaProperties.Size()
		if _, err := m.ImmutableMetaProperties.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ImmutableMetaProperties.Size()))
		i--
		dAtA[i] = 0x4a
	}
	if m.TakerOwnableSplit.Size() > 0 {
		i -= m.TakerOwnableSplit.Size()
		if _, err := m.TakerOwnableSplit.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.TakerOwnableSplit.Size()))
		i--
		dAtA[i] = 0x42
	}
	if m.MakerOwnableSplit.Size() > 0 {
		i -= m.MakerOwnableSplit.Size()
		if _, err := m.MakerOwnableSplit.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.MakerOwnableSplit.Size()))
		i--
		dAtA[i] = 0x3a
	}
	if m.ExpiresIn.Size() > 0 {
		i -= m.ExpiresIn.Size()
		if _, err := m.ExpiresIn.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresIn.Size()))
		i--
		dAtA[i] = 0x32
	}
	if m.TakerOwnableID.Size() > 0 {
		i -= m.TakerOwnableID.Size()
		if _, err := m.TakerOwnableID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.TakerOwnableID.Size()))
		i--
		dAtA[i] = 0x2a
	}
	if m.MakerOwnableID.Size() > 0 {
		i -= m.MakerOwnableID.Size()
		if _, err := m.MakerOwnableID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.MakerOwnableID.Size()))
		i--
		dAtA[i] = 0x22
	}
	if m.ClassificationID.Size() > 0 {
		i -= m.ClassificationID.Size()
		if _, err := m.ClassificationID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ClassificationID.Size()))
		i--
		dAtA[i] = 0x1a
	}
	if m.FromID.Size() > 0 {
		i -= m.FromID.Size()
		if _, err := m.FromID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.FromID.Size()))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.FromID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ClassificationID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MakerOwnableID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TakerOwnableID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ExpiresIn.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MakerOwnableSplit.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TakerOwnableSplit.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ImmutableMetaProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ImmutableProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MutableMetaProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MutableProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = github_com_cosmos_cosmos_sdk_types.AccAddress(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClassificationID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOwnableID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOwnableID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOwnableID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TakerOwnableID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresIn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExpiresIn.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOwnableSplit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOwnableSplit.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOwnableSplit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TakerOwnableSplit.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImmutableMetaProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ImmutableMetaProperties.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImmutableProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ImmutableProperties.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableMetaProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableMetaProperties.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableProperties.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
