// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/identities/transactions/unprovision/tx.proto

package unprovision

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	"github.com/persistenceOne/persistenceSDK/schema/proto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type message struct {
	From       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"from"  valid:"required~required field from missing"`
	To         github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=to,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"to"  valid:"required~required field to missing, matches(^[a-z0-9]*$)~invalid field to"`
	IdentityID types.ID                                      `protobuf:"bytes,3,opt,name=identityID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"identityID"  valid:"required~required field identityID missing"`
}

func (m message) Reset()         { m = message{} }
func (m message) String() string { return proto.CompactTextString(&m) }
func (message) ProtoMessage()    {}
func (*message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a070806591b80fb5, []int{0}
}
func (m *message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *message) XXX_Size() int {
	return m.Size()
}
func (m *message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*message)(nil), "base.message")
}

func init() {
	proto.RegisterFile("proto/identities/transactions/unprovision/tx.proto", fileDescriptor_a070806591b80fb5)
}

var fileDescriptor_a070806591b80fb5 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x3d, 0x6b, 0xdb, 0x40,
	0x18, 0xc7, 0x25, 0xd9, 0xf4, 0xe5, 0x46, 0x41, 0x41, 0xf5, 0x20, 0x95, 0x0e, 0xa5, 0x8b, 0x75,
	0xe0, 0xb6, 0xb4, 0x14, 0x3a, 0xd8, 0xd8, 0x83, 0x69, 0xde, 0xb0, 0xc9, 0x92, 0xc5, 0xc8, 0xd2,
	0x13, 0xf9, 0x88, 0x75, 0xa7, 0xdc, 0xf3, 0x28, 0xc4, 0xdf, 0x20, 0x43, 0x86, 0x7c, 0x04, 0x7f,
	0x1c, 0x8f, 0x1e, 0x43, 0x06, 0x13, 0xec, 0x25, 0x1f, 0x23, 0x44, 0x52, 0xb0, 0x86, 0x04, 0x12,
	0x32, 0x49, 0xc7, 0x3d, 0xff, 0xdf, 0xc3, 0xfd, 0x7f, 0xac, 0x95, 0x6a, 0x45, 0x8a, 0x8b, 0x08,
	0x24, 0x09, 0x12, 0x80, 0x9c, 0x74, 0x20, 0x31, 0x08, 0x49, 0x28, 0x89, 0x3c, 0x93, 0xa9, 0x56,
	0x67, 0x02, 0x85, 0x92, 0x9c, 0xce, 0xfd, 0x7c, 0xd8, 0xae, 0x8f, 0x03, 0x84, 0xc6, 0x37, 0x9a,
	0x08, 0x1d, 0x8d, 0xd2, 0x40, 0xd3, 0x8c, 0x17, 0x94, 0x58, 0xc5, 0x6a, 0xfb, 0x57, 0x4c, 0x37,
	0x7e, 0xbf, 0x7c, 0x83, 0x86, 0xd3, 0x0c, 0x90, 0xca, 0xe0, 0x9f, 0xd7, 0x04, 0x31, 0x55, 0x12,
	0xa1, 0x48, 0x7e, 0xbd, 0xb4, 0xd8, 0xfb, 0x04, 0x10, 0x83, 0x18, 0xec, 0x3e, 0xab, 0x1f, 0x6b,
	0x95, 0x38, 0xe6, 0x17, 0xf3, 0xfb, 0xc7, 0xce, 0xaf, 0xc5, 0xca, 0x33, 0x6e, 0x56, 0x5e, 0x33,
	0x16, 0x34, 0xc9, 0xc6, 0x7e, 0xa8, 0x12, 0x1e, 0x2a, 0x4c, 0x14, 0x96, 0x9f, 0x26, 0x46, 0x27,
	0x9c, 0x66, 0x29, 0xa0, 0xdf, 0x0e, 0xc3, 0x76, 0x14, 0x69, 0x40, 0x1c, 0xe4, 0x08, 0xbb, 0xc7,
	0x2c, 0x52, 0x8e, 0xf5, 0x16, 0x90, 0x45, 0xca, 0x06, 0xc6, 0xca, 0x37, 0xcd, 0xfa, 0x5d, 0xa7,
	0x96, 0xe3, 0x7a, 0x25, 0xee, 0x5f, 0x05, 0x97, 0x82, 0x46, 0x81, 0x04, 0x32, 0x84, 0x7d, 0x09,
	0xd5, 0xe3, 0xb0, 0xfb, 0x9f, 0x63, 0x38, 0x81, 0x24, 0xe0, 0x04, 0x48, 0xa3, 0x62, 0x4d, 0xbf,
	0x3b, 0xa8, 0x80, 0xff, 0x7e, 0xb8, 0x98, 0x7b, 0xc6, 0xdd, 0xdc, 0x33, 0x5a, 0x43, 0x56, 0xdb,
	0xc5, 0xd8, 0xde, 0x61, 0x9f, 0xb6, 0x5d, 0x1e, 0xca, 0x83, 0xc7, 0xf6, 0x6c, 0xc7, 0x7f, 0x10,
	0xea, 0x57, 0xda, 0x1d, 0x14, 0x22, 0x1a, 0x9f, 0x9f, 0xb8, 0x29, 0x9a, 0xee, 0xec, 0x2d, 0xd6,
	0xae, 0xb9, 0x5c, 0xbb, 0xe6, 0xed, 0xda, 0x35, 0xaf, 0x36, 0xae, 0xb1, 0xdc, 0xb8, 0xc6, 0xf5,
	0xc6, 0x35, 0x8e, 0x7e, 0x26, 0x2a, 0xca, 0xa6, 0x80, 0x55, 0x73, 0x42, 0x12, 0x68, 0x19, 0x4c,
	0x9f, 0x55, 0x38, 0x7e, 0x97, 0xab, 0xfb, 0x71, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xad, 0x15,
	0x4f, 0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	IdentitiesUnProvision(ctx context.Context, in *transactionRequest, opts ...grpc.CallOption) (*transactionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) IdentitiesUnProvision(ctx context.Context, in *transactionRequest, opts ...grpc.CallOption) (*transactionResponse, error) {
	out := new(transactionResponse)
	err := c.cc.Invoke(ctx, "/base.Msg/identitiesUnProvision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	IdentitiesUnProvision(context.Context, *transactionRequest) (*transactionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) IdentitiesUnProvision(ctx context.Context, req *transactionRequest) (*transactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentitiesUnProvision not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_IdentitiesUnProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IdentitiesUnProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.Msg/IdentitiesUnProvision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IdentitiesUnProvision(ctx, req.(*transactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "identitiesUnProvision",
			Handler:    _Msg_IdentitiesUnProvision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identities/transactions/unprovision/tx.proto",
}

func (m *message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.IdentityID.Size()
		i -= size
		if _, err := m.IdentityID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := len(m.To)
		i -= size
		if _, err := m.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := len(m.From)
		i -= size
		if _, err := m.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	n += 1 + l + sovTx(uint64(l))
	l = len(m.To)
	n += 1 + l + sovTx(uint64(l))
	l = m.IdentityID.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.To.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IdentityID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
