// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/persistence/assets/orders/transactions/deputize/v1beta1/tx.proto

package deputize

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type message struct {
	From                 github_com_cosmos_cosmos_sdk_types.AccAddress                    `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"from" valid:"required~required field from missing"`
	FromID               github_com_persistenceOne_persistenceSDK_schema_types.ID         `protobuf:"bytes,2,opt,name=fromID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"fromID" valid:"required~required field fromID missing"`
	ToID                 github_com_persistenceOne_persistenceSDK_schema_types.ID         `protobuf:"bytes,3,opt,name=toID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"toID" valid:"required~required field toID missing"`
	ClassificationID     github_com_persistenceOne_persistenceSDK_schema_types.ID         `protobuf:"bytes,4,opt,name=classificationID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"classificationID" valid:"required~required field classificationID missing"`
	MaintainedProperties github_com_persistenceOne_persistenceSDK_schema_types.Properties `protobuf:"varint,5,opt,name=maintainedProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"maintainedProperties" valid:"required~required field maintainedProperties missing"`
	AddMaintainer        bool                                                             `protobuf:"varint,6,opt,name=addMaintainer,proto3" json:"addMaintainer,omitempty" valid:"required~required field addMaintainer missing"`
	RemoveMaintainer     bool                                                             `protobuf:"varint,7,opt,name=removeMaintainer,proto3" json:"removeMaintainer,omitempty" valid:"required~required field removeMaintainer missing"`
	MutateMaintainer     bool                                                             `protobuf:"varint,8,opt,name=mutateMaintainer,proto3" json:"mutateMaintainer,omitempty" valid:"required~required field mutateMaintainer missing"`
}

func (m message) Reset()         { m = message{} }
func (m message) String() string { return proto.CompactTextString(&m) }
func (message) ProtoMessage()    {}
func (*message) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e42e7236adb4bc, []int{0}
}
func (m *message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *message) XXX_Size() int {
	return m.Size()
}
func (m *message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*message)(nil), "persistence.assets.orders.transactions.deputize.v1beta1.message")
}

func init() {
	proto.RegisterFile("proto/persistence/assets/orders/transactions/deputize/v1beta1/tx.proto", fileDescriptor_26e42e7236adb4bc)
}

var fileDescriptor_26e42e7236adb4bc = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd3, 0xc1, 0x6a, 0xd4, 0x40,
	0x18, 0x07, 0xf0, 0x44, 0xd7, 0xed, 0x3a, 0x20, 0x94, 0xe0, 0x21, 0x78, 0xc8, 0x16, 0x11, 0x29,
	0xc2, 0xce, 0x50, 0x44, 0x14, 0x4f, 0xed, 0x12, 0xd4, 0x20, 0xa2, 0xac, 0x1e, 0xc4, 0x8b, 0xcc,
	0xce, 0x7c, 0xdd, 0x1d, 0xdc, 0x99, 0x09, 0xf3, 0x7d, 0x5b, 0xac, 0xf8, 0x00, 0x1e, 0x7d, 0x84,
	0x3e, 0x4e, 0x8f, 0x3d, 0x8a, 0x87, 0x22, 0xbb, 0x17, 0x1f, 0xc1, 0xa3, 0x6c, 0x92, 0xda, 0x68,
	0x7b, 0x92, 0x3d, 0x4d, 0xf2, 0xe5, 0xcf, 0xef, 0x9f, 0x84, 0x19, 0xf6, 0xa4, 0x0c, 0x9e, 0xbc,
	0x28, 0x21, 0xa0, 0x41, 0x02, 0xa7, 0x40, 0x48, 0x44, 0x20, 0x14, 0x3e, 0x68, 0x08, 0x28, 0x28,
	0x48, 0x87, 0x52, 0x91, 0xf1, 0x0e, 0x85, 0x86, 0x72, 0x4e, 0xe6, 0x13, 0x88, 0x83, 0x9d, 0x31,
	0x90, 0xdc, 0x11, 0xf4, 0x91, 0x57, 0x40, 0xf2, 0xb0, 0x25, 0xf0, 0x5a, 0xe0, 0xb5, 0xc0, 0xdb,
	0x02, 0x3f, 0x13, 0x78, 0x23, 0xdc, 0xba, 0x4b, 0x53, 0x13, 0xf4, 0xfb, 0x52, 0x06, 0x3a, 0x14,
	0xf5, 0xcb, 0x4c, 0xfc, 0xc4, 0x9f, 0x5f, 0xd5, 0x05, 0xb7, 0x7f, 0x75, 0xd8, 0x86, 0x05, 0x44,
	0x39, 0x81, 0xa4, 0x60, 0x9d, 0xfd, 0xe0, 0x6d, 0x1a, 0x6f, 0xc5, 0xdb, 0xd7, 0x87, 0x0f, 0x8e,
	0x4f, 0xfb, 0xd1, 0xf7, 0xd3, 0xfe, 0x60, 0x62, 0x68, 0x3a, 0x1f, 0x73, 0xe5, 0xad, 0x50, 0x1e,
	0xad, 0xc7, 0x66, 0x19, 0xa0, 0xfe, 0x20, 0xe8, 0xb0, 0x04, 0xe4, 0x7b, 0x4a, 0xed, 0x69, 0x1d,
	0x00, 0x71, 0x54, 0x11, 0xc9, 0x5b, 0xd6, 0x5d, 0xad, 0x45, 0x9e, 0x5e, 0xa9, 0xb0, 0xdd, 0x06,
	0x7b, 0xd4, 0xc2, 0x5a, 0x9f, 0xf6, 0xd2, 0x41, 0xfb, 0xf6, 0x75, 0xfe, 0x5c, 0xa0, 0x9a, 0x82,
	0x95, 0x8d, 0x5f, 0xe4, 0xa3, 0xc6, 0x4b, 0xde, 0xb0, 0x0e, 0xf9, 0x22, 0x4f, 0xaf, 0xae, 0xc9,
	0xad, 0xb4, 0x64, 0xc6, 0x36, 0xd5, 0x4c, 0x22, 0x9a, 0x7d, 0xa3, 0xe4, 0xea, 0x97, 0x16, 0x79,
	0xda, 0x59, 0x53, 0xc3, 0x05, 0x39, 0xf9, 0xcc, 0x6e, 0x5a, 0x69, 0x1c, 0x49, 0xe3, 0x40, 0xbf,
	0x0a, 0xbe, 0x84, 0x40, 0x06, 0x30, 0xbd, 0xb6, 0x15, 0x6f, 0xf7, 0x86, 0xcf, 0x9a, 0xc6, 0xdd,
	0xff, 0x6b, 0x3c, 0xf7, 0x46, 0x97, 0xb6, 0x24, 0x77, 0xd8, 0x0d, 0xa9, 0xf5, 0x8b, 0xb3, 0x47,
	0x21, 0xed, 0xae, 0x6a, 0x47, 0x7f, 0x0f, 0x93, 0x7b, 0x6c, 0x33, 0x80, 0xf5, 0x07, 0xd0, 0x0a,
	0x6e, 0x54, 0xc1, 0x0b, 0xf3, 0x55, 0xd6, 0xce, 0x49, 0x52, 0x3b, 0xdb, 0xab, 0xb3, 0xff, 0xce,
	0x1f, 0xf7, 0xbe, 0x1c, 0xf5, 0xa3, 0x9f, 0x47, 0xfd, 0x68, 0xf8, 0xf4, 0x78, 0x91, 0xc5, 0x27,
	0x8b, 0x2c, 0xfe, 0xb1, 0xc8, 0xe2, 0xaf, 0xcb, 0x2c, 0x3a, 0x59, 0x66, 0xd1, 0xb7, 0x65, 0x16,
	0xbd, 0x1b, 0x58, 0xaf, 0xe7, 0x33, 0xf8, 0x73, 0x58, 0x8c, 0x23, 0x08, 0x4e, 0xce, 0x2e, 0x3f,
	0x35, 0xe3, 0x6e, 0xb5, 0x95, 0xef, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x80, 0x30, 0xef, 0x82,
	0x75, 0x03, 0x00, 0x00,
}

func (m *message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MutateMaintainer {
		i--
		if m.MutateMaintainer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.RemoveMaintainer {
		i--
		if m.RemoveMaintainer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.AddMaintainer {
		i--
		if m.AddMaintainer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.MaintainedProperties.Size() > 0{
		i -= m.MaintainedProperties.Size()
		if _, err := m.MaintainedProperties.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.MaintainedProperties.Size()))
		i--
		dAtA[i] = 0x28
	}
	if m.ClassificationID.Size() > 0 {
		i -= m.ClassificationID.Size()
		if _, err := m.ClassificationID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ClassificationID.Size()))
		i--
		dAtA[i] = 0x22
	}
	if m.ToID.Size() > 0 {
		i -= m.ToID.Size()
		if _, err := m.ToID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.ToID.Size()))
		i--
		dAtA[i] = 0x1a
	}
	if m.FromID.Size() > 0 {
		i -= m.FromID.Size()
		if _, err := m.FromID.MarshalTo(dAtA[i:]); err!=nil {return 0, err}
		i = encodeVarintTx(dAtA, i, uint64(m.FromID.Size()))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.FromID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ToID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ClassificationID.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MaintainedProperties.Size()
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AddMaintainer {
		n += 2
	}
	if m.RemoveMaintainer {
		n += 2
	}
	if m.MutateMaintainer {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = github_com_cosmos_cosmos_sdk_types.AccAddress(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ToID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClassificationID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClassificationID.Unmarshal(dAtA[iNdEx:postIndex]); err!=nil {return err}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddMaintainer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddMaintainer = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveMaintainer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RemoveMaintainer = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutateMaintainer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MutateMaintainer = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
