// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/persistence/assets/splits/auxiliaries/burn/v1beta1/request.proto

package burn

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type auxiliaryRequest struct {
	OwnerID   github_com_persistenceOne_persistenceSDK_schema_types.ID `protobuf:"bytes,1,opt,name=ownerID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"ownerID" valid:"required~required field ownerID missing"`
	OwnableID github_com_persistenceOne_persistenceSDK_schema_types.ID `protobuf:"bytes,2,opt,name=ownableID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"ownableID" valid:"required~required field ownableID missing"`
	Value     github_com_cosmos_cosmos_sdk_types.Dec                   `protobuf:"bytes,3,opt,name=value,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"value" valid:"required~required field value missing"`
}

func (m *auxiliaryRequest) Reset()         { *m = auxiliaryRequest{} }
func (m *auxiliaryRequest) String() string { return proto.CompactTextString(m) }
func (*auxiliaryRequest) ProtoMessage()    {}
func (*auxiliaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54c034411af27fa, []int{0}
}
func (m *auxiliaryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *auxiliaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuxiliaryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *auxiliaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuxiliaryRequest.Merge(m, src)
}
func (m *auxiliaryRequest) XXX_Size() int {
	return m.Size()
}
func (m *auxiliaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuxiliaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuxiliaryRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*auxiliaryRequest)(nil), "persistence.assets.splits.auxiliaries.burn.v1beta1.auxiliaryRequest")
}

func init() {
	proto.RegisterFile("proto/persistence/assets/splits/auxiliaries/burn/v1beta1/request.proto", fileDescriptor_e54c034411af27fa)
}

var fileDescriptor_e54c034411af27fa = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd1, 0xbf, 0x4e, 0xf3, 0x30,
	0x10, 0x00, 0xf0, 0xa4, 0x9f, 0x3e, 0xa0, 0x99, 0x50, 0xa6, 0x8a, 0xc1, 0x41, 0x0c, 0x15, 0x0b,
	0xb6, 0x0a, 0x0b, 0x30, 0xa1, 0xca, 0x42, 0xaa, 0x18, 0x90, 0xca, 0xd6, 0x01, 0xe4, 0xa4, 0xa7,
	0xd6, 0x22, 0x89, 0x83, 0xcf, 0x6e, 0xe9, 0x1b, 0x30, 0xf2, 0x04, 0xa8, 0x8f, 0xd3, 0xb1, 0x23,
	0x62, 0xa8, 0x50, 0xbb, 0xf0, 0x18, 0x88, 0x3a, 0x55, 0xb3, 0xb0, 0x31, 0xd9, 0x37, 0xdc, 0xef,
	0xfe, 0x05, 0xd7, 0x85, 0x56, 0x46, 0xb1, 0x02, 0x34, 0x4a, 0x34, 0x90, 0x27, 0xc0, 0x04, 0x22,
	0x18, 0x64, 0x58, 0xa4, 0xd2, 0x20, 0x13, 0xf6, 0x59, 0xa6, 0x52, 0x68, 0x09, 0xc8, 0x62, 0xab,
	0x73, 0x36, 0x6a, 0xc5, 0x60, 0x44, 0x8b, 0x69, 0x78, 0xb2, 0x80, 0x86, 0xae, 0x81, 0xf0, 0xb4,
	0x22, 0x50, 0x27, 0x50, 0x27, 0xd0, 0x8a, 0x40, 0x7f, 0x04, 0x5a, 0x0a, 0x07, 0x4d, 0x33, 0x94,
	0xba, 0xff, 0x50, 0x08, 0x6d, 0x26, 0xcc, 0xf5, 0x31, 0x50, 0x03, 0xb5, 0xfd, 0x39, 0xfb, 0xe8,
	0xad, 0x16, 0xec, 0x6f, 0x90, 0x49, 0xd7, 0x95, 0x0d, 0x7b, 0xc1, 0xae, 0x1a, 0xe7, 0xa0, 0x3b,
	0xbc, 0xe1, 0x1f, 0xfa, 0xc7, 0xf5, 0xf6, 0xd5, 0x6c, 0x11, 0x79, 0x1f, 0x8b, 0xe8, 0x7c, 0x20,
	0xcd, 0xd0, 0xc6, 0x34, 0x51, 0x59, 0x75, 0xac, 0xdb, 0x1c, 0xaa, 0xe1, 0x1d, 0xbf, 0x61, 0x98,
	0x0c, 0x21, 0x13, 0xcc, 0x4c, 0x0a, 0x40, 0xda, 0xe1, 0xdd, 0x0d, 0x18, 0xde, 0x07, 0x75, 0x35,
	0xce, 0x45, 0x9c, 0x42, 0x87, 0x37, 0x6a, 0x7f, 0xa4, 0x6f, 0xc9, 0x90, 0x07, 0xff, 0x47, 0x22,
	0xb5, 0xd0, 0xf8, 0xb7, 0xb6, 0x69, 0x69, 0x37, 0x2b, 0x76, 0xa2, 0x30, 0x53, 0x58, 0x3e, 0x27,
	0xd8, 0x7f, 0x2c, 0x21, 0x0e, 0x49, 0xd7, 0x25, 0x5f, 0xee, 0xbd, 0x4c, 0x23, 0xef, 0x6b, 0x1a,
	0x79, 0xed, 0x8b, 0xd9, 0x92, 0xf8, 0xf3, 0x25, 0xf1, 0x3f, 0x97, 0xc4, 0x7f, 0x5d, 0x11, 0x6f,
	0xbe, 0x22, 0xde, 0xfb, 0x8a, 0x78, 0xbd, 0x28, 0x53, 0x7d, 0x9b, 0xc2, 0xaf, 0xd7, 0x8c, 0x77,
	0xd6, 0x2b, 0x3e, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x9b, 0xc8, 0xaf, 0x08, 0x02, 0x00,
	0x00,
}

func (m *auxiliaryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *auxiliaryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *auxiliaryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value.Size() > 0 {
		i -= m.Value.Size()
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRequest(dAtA, i, uint64(m.Value.Size()))
		i--
		dAtA[i] = 0x1a
	}
	if m.OwnableID.Size() > 0 {
		i -= m.OwnableID.Size()
		if _, err := m.OwnableID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRequest(dAtA, i, uint64(m.OwnableID.Size()))
		i--
		dAtA[i] = 0x12
	}
	if m.OwnerID.Size() > 0 {
		i -= m.OwnerID.Size()
		if _, err := m.OwnerID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRequest(dAtA, i, uint64(m.OwnerID.Size()))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *auxiliaryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OwnerID.Size()
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = m.OwnableID.Size()
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = m.Value.Size()
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	return n
}

func sovRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRequest(x uint64) (n int) {
	return sovRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *auxiliaryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: auxiliaryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: auxiliaryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OwnerID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnableID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OwnableID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRequest = fmt.Errorf("proto: unexpected end of group")
)
